#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.12.00 (2010-12-09)
# user:         sam
# date:         Tue Jan 18 11:03:05 MST 2011
# host:         AMAZON
# directory:    C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\ReadCropPatternTSFromHydroBase
# command line: StateDMI -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\ReadCropPatternTSFromHydroBase\Test_ReadCropPatternTSFromHydroBase.StateDMI"
# Commands: 
# # Test fill CU location data from HydroBase
# StartLog(LogFile="Results/Test_ReadCropPatternTSFromHydroBase.StateDMI.log")
# RemoveFile(InputFile="Results\Test_ReadCropPatternTSFromHydroBase_out.cds",IfNotFound=Ignore)
# SetOutputPeriod(OutputStart="1950",OutputEnd="2007")
# SetCULocation(ID="2000505",IfNotFound=Add)
# SetCULocation(ID="2000631",IfNotFound=Add)
# SetCULocation(ID="2000812",IfNotFound=Add)
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# ReadCropPatternTSFromHydroBase(ID="*")
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_ReadCropPatternTSFromHydroBase_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_out.cds",InputFile2="Results/Test_ReadCropPatternTSFromHydroBase_out.cds",IfDifferent=Warn)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on Lonetree\CDSS
# HydroBase.db_version:  design version: 20080701  last data change: 20100801
# HydroBase table structure for software is at least 2007052520070525
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      1950           2007 ACRE CYR  
1950 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1950 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1950 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1951 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1951 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1951 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1952 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1952 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1952 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1953 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1953 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1953 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1954 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1954 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1954 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1955 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1955 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1955 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1956 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1956 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1956 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1957 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1957 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1957 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1958 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1958 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1958 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1959 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1959 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1959 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1960 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1960 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1960 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1961 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1961 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1961 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1962 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1962 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1962 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1963 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1963 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1963 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1964 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1964 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1964 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1965 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1965 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1965 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1966 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1966 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1966 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1967 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1967 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1967 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1968 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1968 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1968 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1969 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1969 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1969 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1970 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1970 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1970 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1971 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1971 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1971 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1972 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1972 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1972 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1973 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1973 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1973 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1974 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1974 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1974 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1975 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1975 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1975 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1976 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1976 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1976 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1977 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1977 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1977 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1978 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1978 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1978 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1979 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1979 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1979 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1980 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1980 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1980 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1981 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1981 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1981 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1982 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1982 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1982 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1983 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1983 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1983 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1984 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1984 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1984 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1985 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1985 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1985 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1986 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1986 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1986 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1987 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1987 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1987 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1988 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1988 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1988 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1989 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1989 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1989 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1990 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1990 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1990 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1991 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1991 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1991 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1992 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1992 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1992 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1993 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1993 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1993 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1994 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1994 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1994 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1995 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1995 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1995 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1996 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1996 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1996 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1997 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1997 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1997 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1998 2000505                         1212.657         1
     GRASS_PASTURE                      1.000  1212.657
1998 2000631                        49199.449         5
     ALFALFA                            0.070  3439.792
     GRASS_PASTURE                      0.031  1547.379
     POTATOES                           0.466 22904.074
     SMALL_GRAINS                       0.403 19850.150
     VEGETABLES                         0.030  1458.054
1998 2000812                        81451.940         5
     ALFALFA                            0.253 20591.756
     GRASS_PASTURE                      0.145 11824.366
     POTATOES                           0.267 21751.820
     SMALL_GRAINS                       0.312 25400.852
     VEGETABLES                         0.023  1883.146
1999 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1999 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
1999 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2000 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2000 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2000 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2001 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2001 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2001 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2002 2000505                          422.833         1
     GRASS_PASTURE                      1.000   422.833
2002 2000631                        46743.309         5
     ALFALFA                            0.101  4726.517
     GRASS_PASTURE                      0.006   267.396
     POTATOES                           0.475 22204.387
     SMALL_GRAINS                       0.395 18450.449
     VEGETABLES                         0.023  1094.560
2002 2000812                        73622.234         5
     ALFALFA                            0.363 26719.404
     GRASS_PASTURE                      0.060  4427.934
     POTATOES                           0.276 20283.750
     SMALL_GRAINS                       0.279 20552.615
     VEGETABLES                         0.022  1638.531
2003 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2003 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2003 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2004 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2004 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2004 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2005 2000505                          578.108         1
     GRASS_PASTURE                      1.000   578.108
2005 2000631                        41959.023         5
     ALFALFA                            0.094  3958.677
     GRASS_PASTURE                      0.067  2808.386
     POTATOES                           0.446 18723.307
     SMALL_GRAINS                       0.355 14900.533
     VEGETABLES                         0.037  1568.120
2005 2000812                        70170.011         5
     ALFALFA                            0.371 26023.844
     GRASS_PASTURE                      0.092  6448.034
     POTATOES                           0.274 19242.988
     SMALL_GRAINS                       0.248 17374.324
     VEGETABLES                         0.015  1080.821
2006 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2006 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2006 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2007 2000505                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2007 2000631                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
2007 2000812                         -999.000         5
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     POTATOES                        -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
     VEGETABLES                      -999.000  -999.000
