# THIS VERSION GENERATED AS REFORMAT OF VERSION 10 - HAS ROUNDOFF
#HeaderRevision 0
#
# File generated by...
# program:   StateDMI 2.01.00 (2007-01-04)
# user:      kat
# date:      Wed Jan 10 11:29:05 MST 2007
# host:      cimarron
# directory: C:\Documents and Settings\kat\Desktop
# command:   StateDMI -home test\operational\CDSS 
#-----------------------------------------------------------------------
# Last command file: "C:\Documents and Settings\kat\Desktop\cropPattern.StateDMi"
#
# Commands used to generate output:
#
# readCropPatternTSFromStateCU(InputFile="C:\Documents and Settings\kat\My Documents\DataSets\StateCU\2005\cm2005.cds")
# writeCropPatternTSToStateCU(OutputFile="C:\Documents and Settings\kat\Desktop\new",WriteHow=OverwriteFile)
#----
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on hbserver
# HydroBase.db_version:  design version: 20061003  last data change: 20060816
# HydroBase table structure for software is at least 2005111520051115
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (i5,1x,i4,5x,i5,1x,i4,a5,a5)
#>
#>  month1           :  Beginning month of data (always 1).
#>  year1            :  Beginning year of data (calendar year).
#>  month2           :  Ending month of data (always 12).
#>  year2            :  Ending year of data (calendar year).
#>  units            :  Data units for crop areas.
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10)- for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0).
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop (equal to total
#>                      * fraction as shown in file.
#>
#>Yr  CULocation     TotalArea       NCrop
#>-exb----------exxxxxxxxb--------eb--------e
#>     CropName          Fraction    Acres
#>xxxb------------------eb--------eb--------e
#>EndHeader
      2002           2003 ACRE CYR
# Negative fraction and part
2002 360645                           355.962         1
     GRASS_PASTURE                     -1.000  -355.962
# Zero area for full time series
2002 360649                             0.000         1
     GRASS_PASTURE                      1.000     0.000
# Zero number of crops for full time series
2002 360660                             0.000         0
# Total does not add to parts...
2002 360662                          3368.798         2
     ALFALFA                            1.085   201.348
     GRASS_PASTURE                      0.915  2167.450
# Negative total (not a problem because total is computed from parts)...
2002 370548                          -210.147         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      1.000   210.147
     SMALL_GRAINS                       0.000     0.000
# Negative fraction and part
2003 360645                           355.962         1
     GRASS_PASTURE                     -1.000  -355.962
2003 360649                             0.000         1
     GRASS_PASTURE                      1.000     0.000
2003 360660                             0.000         0
# Total does not add to parts...
2003 360662                          3368.798         2
     ALFALFA                            1.085   201.348
     GRASS_PASTURE                      0.915  2167.450
# Negative total (not a problem because total is computed from parts)...
2003 370548                          -210.147         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      1.000   210.147
     SMALL_GRAINS                       0.000     0.000
