#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.02.00 beta (2008-10-07)
# user:         sam
# date:         Sat Jan 03 23:24:26 MST 2009
# host:         SOPRIS
# directory:    C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\FillCropPatternTSRepeat
# command line: StateDMI -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\FillCropPatternTSRepeat\Test_FillCropPatternTSRepeat.StateDMI"
# Commands: 
# # Test filling crop pattern time series data by repeating values
# StartLog(LogFile="Results/Test_FillCropPatternTSRepeat.StateDMI.log")
# RemoveFile(InputFile="Results\Test_FillCropPatternTSRepeat_out.cds")
# SetCULocation(ID="2000505",IfNotFound=Add)
# SetCULocation(ID="2000623",IfNotFound=Add)
# SetCULocation(ID="2000812",IfNotFound=Add)
# SetOutputPeriod(OutputStart="1998",OutputEnd="2002")
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# SetCropPatternTS(ID="2000505",SetStart=1998,SetEnd=1998,CropPattern="ALFALFA,101,CORN,102",IrrigationMethod=Flood,SupplyType=Ground)
# SetCropPatternTS(ID="2000623",SetStart=1998,SetEnd=2000,CropPattern="ALFALFA,201,CORN,202",IrrigationMethod=Sprinkler,SupplyType=Surface)
# SetCropPatternTS(ID="2000812",SetStart=1998,SetEnd=2002,CropPattern="ALFALFA,301,CORN,302",IrrigationMethod=Sprinkler,SupplyType=Ground)
# FillCropPatternTSRepeat(ID="*",CropType="*")
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_FillCropPatternTSRepeat_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_FillCropPatternTSRepeat_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_FillCropPatternTSRepeat_out.cds",InputFile2="Results/Test_FillCropPatternTSRepeat_out.cds",WarnIfDifferent=True)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on hbserver
# HydroBase.db_version:  design version: 20080701  last data change: 20080901
# HydroBase table structure for software is at least 2007052520070525
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      1998           2002 ACRE CYR  
1998 2000505                          203.000         2
     ALFALFA                            0.498   101.000
     CORN                               0.502   102.000
1998 2000623                          403.000         2
     ALFALFA                            0.499   201.000
     CORN                               0.501   202.000
1998 2000812                          603.000         2
     ALFALFA                            0.499   301.000
     CORN                               0.501   302.000
1999 2000505                          203.000         2
     ALFALFA                            0.498   101.000
     CORN                               0.502   102.000
1999 2000623                          403.000         2
     ALFALFA                            0.499   201.000
     CORN                               0.501   202.000
1999 2000812                          603.000         2
     ALFALFA                            0.499   301.000
     CORN                               0.501   302.000
2000 2000505                          203.000         2
     ALFALFA                            0.498   101.000
     CORN                               0.502   102.000
2000 2000623                          403.000         2
     ALFALFA                            0.499   201.000
     CORN                               0.501   202.000
2000 2000812                          603.000         2
     ALFALFA                            0.499   301.000
     CORN                               0.501   302.000
2001 2000505                          203.000         2
     ALFALFA                            0.498   101.000
     CORN                               0.502   102.000
2001 2000623                          403.000         2
     ALFALFA                            0.499   201.000
     CORN                               0.501   202.000
2001 2000812                          603.000         2
     ALFALFA                            0.499   301.000
     CORN                               0.501   302.000
2002 2000505                          203.000         2
     ALFALFA                            0.498   101.000
     CORN                               0.502   102.000
2002 2000623                          403.000         2
     ALFALFA                            0.499   201.000
     CORN                               0.501   202.000
2002 2000812                          603.000         2
     ALFALFA                            0.499   301.000
     CORN                               0.501   302.000
