# THIS FILE HAS BEEN HAND EDITED TO INTRODUCE ERRORS FOR CHECKS
#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.07.00 (2009-05-11)
# user:         sam
# date:         Mon May 25 03:17:16 MDT 2009
# host:         SOPRIS
# directory:    C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\TestSuites\commands\run
# command line: StateDMI
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\WriteReservoirStationsToStateMod\Test_WriteReservoirStationsToStateMod_cm2005.StateDMI"
# Commands: 
# # Test writing reservoir stations to StateMod file - use full Colorado file for input
# StartLog(LogFile="Results/Test_WriteReservoirStationsToStateMod_cm2005.StateDMI.log")
# RemoveFile(InputFile="Results\Test_WriteReservoirStationsToStateMod_cm2005_out.res")
# ReadReservoirStationsFromStateMod(InputFile="Data\cm2005.res")
# # Write the file again and compare with the original file.
# WriteReservoirStationsToStateMod(OutputFile="Results/Test_WriteReservoirStationsToStateMod_cm2005_out.res")
# CompareFiles(InputFile1="Data/cm2005.res",InputFile2="Results/Test_WriteReservoirStationsToStateMod_cm2005_out.res",WarnIfDifferent=True)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on hbserver
# HydroBase.db_version:  design version: 20080701  last data change: 20080901
# HydroBase table structure for software is at least 2007052520070525
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#> *************************************************************
#>  StateMod Reservoir Station file
#>
#>  Card 1   format:  (a12, a24, a12, i8, f8.0, 1x, a12)
#>
#>  ID       cresid:  Reservoir Id
#>  Name     resnam:  Reservoir name
#>  Riv ID    cgoto:  Node where Reservoir is located
#>  On/Off   iressw:  Switch 0 = off, 1 = on
#>  Admin #   rdate:  Administration date for 1 fill rule
#>  Daily ID cresdy:  Identifier for daily time series.
#>
#>  Card 2 format:  (24x, 4f8.0, 4i8)
#>
#>  VolMin   volmin:  Min storage (ac-ft)
#>  VolMax   volmax:  Max storage (ac-ft)
#>  FloMax   flomax:  Max discharge (cfs)
#>  DeadSt   deadst:  Dead storage (ac-ft)
#>  NumOwner nowner:  Number of owners
#>  NumEva   nevapo:  Number of evaporation stations
#>  NumPre   nprecp:  Number of precipitation stations
#>  NumTable nrange:  Number of area capacity values
#>
#>     Card 3 format:  (12x, a12, 3f8.0, i8)
#>
#>  OwnName  ownnam:  Owner name
#>  OwnMax   ownmax:  Maximum storage for that owner (ac-ft)
#>  Sto-1    curown:  Initial storage for that owner (ac-ft)
#>  EvapTyp  pcteva:  Evaporation distribution
#>  FillTyp   n2own:  Ownership type 1=First fill; 2=Second fill
#>
#>  Card 4  format:  (24x, a12, f8.0)
#>
#>  Evap ID  cevar:  Evaporation station
#>  EvapWt  weigev:  Evaporation station weight (%%)
#>
#>  Card 5 format:  (24x, a12, f8.0)
#>
#>  Prec ID   cprer:  Precipitation station
#>  PrecWt   weigpr:  Precipitation station weight (%%)
#>
#>  Card 6 format:  (24x, 3f8.0)
#>     Cont     conten:  Content (ac-ft)
#>     Area    surarea:  Area (ac)
#>     Seep    seepage:  Seepage (ac-ft)
#>
#> *************************************************************
#>
#>    ID              Name              Node     On/Off  RDate       DailyID 
#>---------eb----------------------eb----------eb------eb------exb----------e
#>                       VolMin  VolMax  FloMax  DeadSt NumOwner NumEva  NumPre NumTable
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------eb------eb------eb------eb------eb------e
#>                         OwnName   OwnMax   Sto-1 EvapTyp FillTyp
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------eb------eb------eb------e
#>                        Evap Id    EvapWt 
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Prec Id    PrecWt 
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Cont    Area    Seep  
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------e
#>EndHeader
#>
363543                              999999            -3     -4.  -5           
                            -10. -54645.  -4010.    -10.       6       1       0      14
                         -66000.      0.       0       1
            CBT_Pool     152000.    -10.     -10      -1
            Contract      20000.      0.       0       1
            Silt_Proj      5000.      0.       0       1
            Inactive      11645.      0.       0       1
            SurplusFish   66000.      0.       0       1
            Evaporation 10008           -90.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     291.   20.00       0
            CAP-AREA  2     938.   47.00       0
            CAP-AREA  3     316.   95.00       0
            CAP-AREA  4    4912.      70       0
            CAP-AREA  5    9366.     282       0
            CAP-AREA  6   16557.     445       0
            CAP-AREA  7   26999.     596       0
            CAP-AREA  8   40845.     809       0
            CAP-AREA  9   59397.    1060       0
            CAP-AREA 10   83777.    1375       0
            CAP-AREA 11  114862.    1755       0
            CAP-AREA 12  153639.    2124       0
            CAP-AREA 13 9999999.    2124       0
363570      CONT_HOOSIER_BLUE_RES   363570             1      4. 5           
                              0.   2113. 999999.      0.       2       1       0       3
            Active         2140.      0.       0       1
            CSprings-OOP   2100.      0.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2140.     214       0
            CAP-AREA  2 9999999.     214       0
