#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.12.00 (2010-12-09)
# user:         sam
# date:         Tue Jan 18 09:42:53 MST 2011
# host:         AMAZON
# directory:    C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\FillCropPatternTSUsingWellRights
# command line: StateDMI -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\FillCropPatternTSUsingWellRights\Test_FillCropPatternTSUsingWellRights.StateDMI"
# Commands: 
# # Test filling crop pattern time series data using well rights
# #@expectedStatus Warning (because some minor warnings from fill command)
# StartLog(LogFile="Results/Test_FillCropPatternTSUsingWellRights.StateDMI.log")
# RemoveFile(InputFile="Results\Test_FillCropPatternTSUsingWellRights_out.cds")
# SetCULocation(ID="2000505",IfNotFound=Add)
# SetCULocation(ID="2000623",IfNotFound=Add)
# SetCULocation(ID="2000812",IfNotFound=Add)
# SetOutputPeriod(OutputStart="1998",OutputEnd="2002")
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# # Currently cannot use assigned data because parcel IDs are defaulted to -1.
# # Need to evaluate allowing users to assign parcel identifiers (negative numbers?)
# # so that filling works.  For now read the data from HydroBase.
# # SetCropPatternTS(ID="2000505",SetStart=1998,SetEnd=1998,CropPattern="ALFALFA,101,CORN,102",IrrigationMethod=Flood,SupplyType=Ground)
# # SetCropPatternTS(ID="2000623",SetStart=1998,SetEnd=2000,CropPattern="ALFALFA,201,CORN,202",IrrigationMethod=Sprinkler,SupplyType=Surface)
# # SetCropPatternTS(ID="2000812",SetStart=1998,SetEnd=2002,CropPattern="ALFALFA,301,CORN,302",IrrigationMethod=Sprinkler,SupplyType=Ground)
# ReadCropPatternTSFromHydroBase(ID="*")
# SetWellRight(ID="2000505.01",Name="Right1",StationID="2000505",AdministrationNumber=45000.00000,Decree=50,IfNotFound=Add)
# # The following does not work because acreage is not read from a parcel
# # basis - need to evaluate command.
# FillCropPatternTSUsingWellRights(ID="*",CropType="*",ParcelYear=1998)
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_FillCropPatternTSUsingWellRights_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_FillCropPatternTSUsingWellRights_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_FillCropPatternTSUsingWellRights_out.cds",InputFile2="Results/Test_FillCropPatternTSUsingWellRights_out.cds",IfDifferent=Fail)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on Lonetree\CDSS
# HydroBase.db_version:  design version: 20080701  last data change: 20100801
# HydroBase table structure for software is at least 2007052520070525
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      1998           2002 ACRE CYR  
1998 2000505                         1212.657         1
     GRASS_PASTURE                      1.000  1212.657
1998 2000623                        35855.552         5
     ALFALFA                            0.369 13232.553
     GRASS_PASTURE                      0.481 17239.176
     POTATOES                           0.014   487.242
     SMALL_GRAINS                       0.133  4769.617
     VEGETABLES                         0.004   126.964
1998 2000812                        81451.940         5
     ALFALFA                            0.253 20591.756
     GRASS_PASTURE                      0.145 11824.366
     POTATOES                           0.267 21751.820
     SMALL_GRAINS                       0.312 25400.852
     VEGETABLES                         0.023  1883.146
1999 2000505                            0.000         1
     GRASS_PASTURE                      0.000     0.000
1999 2000623                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
1999 2000812                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
2000 2000505                            0.000         1
     GRASS_PASTURE                      0.000     0.000
2000 2000623                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
2000 2000812                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
2001 2000505                            0.000         1
     GRASS_PASTURE                      0.000     0.000
2001 2000623                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
2001 2000812                            0.000         5
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.000     0.000
     POTATOES                           0.000     0.000
     SMALL_GRAINS                       0.000     0.000
     VEGETABLES                         0.000     0.000
2002 2000505                          422.833         1
     GRASS_PASTURE                      1.000   422.833
2002 2000623                        21068.640         5
     ALFALFA                            0.642 13525.753
     GRASS_PASTURE                      0.239  5040.417
     POTATOES                           0.032   680.234
     SMALL_GRAINS                       0.086  1822.235
     VEGETABLES                         0.000     0.000
2002 2000812                        73622.234         5
     ALFALFA                            0.363 26719.404
     GRASS_PASTURE                      0.060  4427.934
     POTATOES                           0.276 20283.750
     SMALL_GRAINS                       0.279 20552.615
     VEGETABLES                         0.022  1638.531
