#HeaderRevision 0
#
# File generated by...
# program:   TSTool 7.01.00 (2007-02-12)
# user:      sam
# date:      Tue Feb 27 15:09:31 MST 2007
# host:      SOPRIS
# directory: J:\CDSS\develop\Support\RayBennett\RayBennett_TSTool_2007-02-26_analyzePattern
# command:   TSTool -home 
#            C:\Develop\TSTool\Java_142\trunk\test\operational\CDSS 
#-----------------------------------------------------------------------
#
# Commands used to generate output:
#
# setOutputYearType(Calendar)
# setOutputPeriod(01/1950,12/2005)
# # 08220000 - RIO GRANDE RIVER NEAR DEL NORTE
# 08220000.USGS.Streamflow.Month~HydroBase
# analyzePattern(TSList=AllMatchingTSID,TSID="08220000.USGS.Streamflow.Month",Method=Percentile,Percentile="0.25,0.75",PatternID="Dry,Ave,Wet",OutputFile="Fill_2005.pat")
# # writeStateMod(TSList=AllTS,OutputFile="Fill_2005.pat")
#------------------------------------------------
#
# StateMod format pattern time series
# ***********************************
#
# Years Shown = Calendar Years
# The period of record for each time series may vary
# because of the original input and data processing steps.
#
#     TS ID                    Type   Source   Units  Period of Record    Location    Description
#   1 08220000_pattern.USGS.St Stream USGS            Jan/1890 - Dec/2005 08220000_patRIO GRANDE RIVER NEAR DE
#
#>EndHeader
#>
#> Yr ID            Jan     Feb     Mar     Apr     May     Jun     Jul     Aug     Sep     Oct     Nov     Dec     
#>-e-b----------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------e
    1/1950  -     12/2005       CYR
1950 08220000_pat     Ave     Ave     Ave     Wet     Ave     Dry     Ave     Dry     Dry     Dry     Dry     Dry
1951 08220000_pat     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry
1952 08220000_pat     Ave     Ave     Dry     Wet     Ave     Wet     Wet     Wet     Ave     Ave     Ave     Ave
1953 08220000_pat     Ave     Ave     Ave     Ave     Dry     Ave     Ave     Dry     Dry     Dry     Dry     Dry
1954 08220000_pat     Dry     Ave     Dry     Ave     Dry     Dry     Ave     Ave     Dry     Ave     Dry     Dry
1955 08220000_pat     Dry     Dry     Dry     Dry     Dry     Ave     Dry     Ave     Dry     Dry     Dry     Dry
1956 08220000_pat     Ave     Dry     Ave     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry
1957 08220000_pat     Dry     Dry     Dry     Ave     Dry     Wet     Wet     Wet     Wet     Ave     Wet     Wet
1958 08220000_pat     Ave     Ave     Dry     Ave     Wet     Ave     Ave     Ave     Ave     Dry     Dry     Dry
1959 08220000_pat     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Ave     Dry     Ave     Ave     Ave
1960 08220000_pat     Ave     Ave     Wet     Wet     Ave     Ave     Ave     Dry     Dry     Dry     Dry     Dry
1961 08220000_pat     Dry     Dry     Dry     Ave     Ave     Ave     Dry     Ave     Ave     Ave     Ave     Ave
1962 08220000_pat     Ave     Wet     Ave     Wet     Ave     Ave     Ave     Ave     Dry     Ave     Ave     Ave
1963 08220000_pat     Dry     Dry     Ave     Ave     Ave     Dry     Dry     Dry     Ave     Dry     Dry     Dry
1964 08220000_pat     Dry     Dry     Dry     Dry     Ave     Dry     Dry     Ave     Dry     Dry     Dry     Dry
1965 08220000_pat     Dry     Dry     Dry     Ave     Wet     Wet     Wet     Wet     Wet     Wet     Wet     Wet
1966 08220000_pat     Ave     Ave     Wet     Ave     Ave     Ave     Ave     Ave     Dry     Dry     Dry     Ave
1967 08220000_pat     Dry     Dry     Ave     Dry     Dry     Dry     Dry     Ave     Ave     Dry     Dry     Dry
1968 08220000_pat     Dry     Dry     Dry     Dry     Ave     Ave     Ave     Wet     Ave     Ave     Ave     Ave
1969 08220000_pat     Ave     Ave     Dry     Ave     Ave     Ave     Ave     Ave     Ave     Wet     Wet     Wet
1970 08220000_pat     Ave     Ave     Dry     Dry     Ave     Ave     Ave     Ave     Wet     Ave     Ave     Ave
1971 08220000_pat     Wet     Wet     Wet     Ave     Dry     Ave     Ave     Dry     Dry     Ave     Ave     Ave
1972 08220000_pat     Ave     Ave     Wet     Ave     Ave     Dry     Dry     Dry     Dry     Ave     Ave     Ave
1973 08220000_pat     Ave     Ave     Ave     Dry     Wet     Wet     Wet     Wet     Ave     Ave     Dry     Ave
1974 08220000_pat     Ave     Ave     Ave     Dry     Ave     Dry     Dry     Dry     Dry     Dry     Dry     Dry
1975 08220000_pat     Dry     Dry     Dry     Dry     Ave     Wet     Wet     Ave     Ave     Ave     Wet     Ave
1976 08220000_pat     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Dry     Dry
1977 08220000_pat     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry
1978 08220000_pat     Dry     Dry     Dry     Dry     Dry     Ave     Ave     Dry     Dry     Ave     Dry     Dry
1979 08220000_pat     Dry     Dry     Dry     Ave     Wet     Wet     Wet     Ave     Ave     Dry     Ave     Ave
1980 08220000_pat     Ave     Wet     Dry     Ave     Ave     Wet     Wet     Ave     Ave     Dry     Dry     Ave
1981 08220000_pat     Ave     Ave     Dry     Ave     Dry     Dry     Dry     Dry     Ave     Wet     Ave     Ave
1982 08220000_pat     Ave     Ave     Ave     Ave     Dry     Ave     Ave     Ave     Wet     Wet     Wet     Wet
1983 08220000_pat     Ave     Ave     Ave     Dry     Dry     Ave     Wet     Ave     Ave     Ave     Ave     Ave
1984 08220000_pat     Ave     Ave     Ave     Dry     Wet     Ave     Ave     Ave     Wet     Wet     Ave     Ave
1985 08220000_pat     Wet     Ave     Ave     Wet     Wet     Wet     Wet     Ave     Wet     Wet     Wet     Wet
1986 08220000_pat     Wet     Wet     Wet     Ave     Ave     Wet     Wet     Wet     Wet     Wet     Wet     Wet
1987 08220000_pat     Wet     Wet     Wet     Wet     Wet     Wet     Wet     Wet     Ave     Ave     Ave     Ave
1988 08220000_pat     Ave     Ave     Ave     Dry     Dry     Ave     Ave     Ave     Ave     Ave     Ave     Ave
1989 08220000_pat     Ave     Ave     Wet     Wet     Ave     Ave     Ave     Dry     Ave     Ave     Dry     Dry
1990 08220000_pat     Dry     Dry     Dry     Dry     Ave     Ave     Ave     Ave     Ave     Wet     Ave     Ave
1991 08220000_pat     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Wet     Dry     Ave     Ave
1992 08220000_pat     Dry     Dry     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Dry     Ave     Dry
1993 08220000_pat     Ave     Dry     Ave     Ave     Ave     Ave     Ave     Ave     Wet     Ave     Ave     Ave
1994 08220000_pat     Ave     Dry     Ave     Ave     Ave     Ave     Ave     Dry     Ave     Ave     Ave     Wet
1995 08220000_pat     Ave     Ave     Wet     Dry     Ave     Wet     Wet     Wet     Wet     Ave     Ave     Ave
1996 08220000_pat     Ave     Ave     Ave     Ave     Ave     Dry     Dry     Dry     Dry     Ave     Ave     Ave
1997 08220000_pat     Ave     Ave     Wet     Ave     Wet     Ave     Wet     Wet     Wet     Wet     Wet     Wet
1998 08220000_pat     Wet     Wet     Wet     Ave     Ave     Ave     Ave     Ave     Ave     Ave     Wet     Wet
1999 08220000_pat     Wet     Ave     Wet     Ave     Ave     Ave     Wet     Wet     Wet     Wet     Wet     Ave
2000 08220000_pat     Ave     Ave     Ave     Ave     Ave     Dry     Dry     Dry     Dry     Ave     Dry     Dry
2001 08220000_pat     Dry     Dry     Ave     Ave     Wet     Ave     Ave     Ave     Ave     Dry     Dry     Dry
2002 08220000_pat     Ave     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry
2003 08220000_pat     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Dry     Ave     Dry     Ave     Dry
2004 08220000_pat     Dry     Dry     Wet     Ave     Ave     Ave     Dry     Dry     Ave     Ave     Ave     Ave
2005 08220000_pat     Ave     Ave     Ave     Wet     Wet     Ave     Ave     Ave     Ave     Wet     Ave     Ave
