#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.09.01 (2010-01-24)
# user:         sam
# date:         Mon Feb 08 11:50:49 MST 2010
# host:         AMAZON
# directory:    C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\SortCropPatternTS
# command line: StateDMI -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Develop\StateDMI_SourceBuild\StateDMI\test\regression\commands\SortCropPatternTS\Test_SortCropPatternTS.StateDMI"
# Commands: 
# # Test sorting crop pattern time series
# StartLog(LogFile="Results/Test_SortCropPatternTS.StateDMI.log")
# RemoveFile(InputFile="Results\Test_SortCropPatternTS_out.cds")
# SetOutputPeriod(OutputStart="2000",OutputEnd="2002")
# SetCULocation(ID="Loc3",IfNotFound=Add)
# SetCULocation(ID="Loc1",IfNotFound=Add)
# SetCULocation(ID="Loc2",IfNotFound=Add)
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# SetCropPatternTS(ID="Loc1",SetStart=2000,SetEnd=2002,CropPattern="ALFALFA,100.1,CORN,100.2",IrrigationMethod=Flood,SupplyType=Surface,ProcessWhen=Now)
# SetCropPatternTS(ID="Loc2",SetStart=2000,SetEnd=2002,CropPattern="ALFALFA,200.1,CORN,200.2",IrrigationMethod=Flood,SupplyType=Surface,ProcessWhen=Now)
# SetCropPatternTS(ID="Loc3",SetStart=2000,SetEnd=2002,CropPattern="ALFALFA,300.1,CORN,300.2",IrrigationMethod=Flood,SupplyType=Surface,ProcessWhen=Now)
# SortCropPatternTS()
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_SortCropPatternTS_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_SortCropPatternTS_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_SortCropPatternTS_out.cds",InputFile2="Results/Test_SortCropPatternTS_out.cds",IfDifferent=Warn)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase on hbserver
# HydroBase.db_version:  design version: 20080701  last data change: 20090701
# HydroBase table structure for software is at least 2007052520070525
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      2000           2002 ACRE CYR  
2000 Loc1                             200.300         2
     ALFALFA                            0.500   100.100
     CORN                               0.500   100.200
2000 Loc2                             400.300         2
     ALFALFA                            0.500   200.100
     CORN                               0.500   200.200
2000 Loc3                             600.300         2
     ALFALFA                            0.500   300.100
     CORN                               0.500   300.200
2001 Loc1                             200.300         2
     ALFALFA                            0.500   100.100
     CORN                               0.500   100.200
2001 Loc2                             400.300         2
     ALFALFA                            0.500   200.100
     CORN                               0.500   200.200
2001 Loc3                             600.300         2
     ALFALFA                            0.500   300.100
     CORN                               0.500   300.200
2002 Loc1                             200.300         2
     ALFALFA                            0.500   100.100
     CORN                               0.500   100.200
2002 Loc2                             400.300         2
     ALFALFA                            0.500   200.100
     CORN                               0.500   200.200
2002 Loc3                             600.300         2
     ALFALFA                            0.500   300.100
     CORN                               0.500   300.200
